version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
      - '1935:1935'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_HOST=mongo
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_PORT=27017
  rtmpserver:
    build:
      dockerfile: Dockerfile.dev
      context: ./rtmpserver
    volumes:
      - /app/node_modules
      - ./rtmpserver:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app